### ISSUE TITLE
Zwift does not find Fortius-ANT device

### ISSUE THREAD

**Issue by slilja** [WouterJD/FortiusANT#422]
After a year's break from Zwift I tried to use it again. Unfortunately things do not work well and I don't know where to start problem solving.
I am running Fortius-ANT on "trainer-laptop" MacBook v11.6.8 BigSur and Zwift on another Macbook (OS 13.2 Ventura). Fortius-ANT seems to start correctly and connects to Bushido brake (UX shows correct cadence & watt etc), but Zwift does not find any devide.
On my previous try (year ago), Zwift showed "trainer-laptop" and I could pair devides easily. Now there are no devices.

Question: How to start debugging the problem? Where is the best branch / version for Tacx Bushido?

**Comment by WouterJD** [comment]
Hi @slilja 

FortiusAnt AND Zwift each need an ANT-dongle to be present. Are you sure there are two?
Do you see Zwift connecting to the ANT-dongle (interface green)?

Check that FortiusAnt works with each dongle (test twice with one dongle only).
Check that Zwift works with each dongle (test twice with one dongle only).

The start both programs; FortiusAnt first and when ready to zwift, start Zwift and check interface.

Please come back when still not working...

**Comment by slilja** [comment]
Hmm. I am not sure if two ANT dongles are needed. In my previous configuration things worked well. I had FortiusANT running on "trainer-laptop" with ANT dongle and Zwift running in another laptop without ANT dongle.
Now the only thing that changed is the other laptop. I am still using the same "trainer-laptop" with ANT and running FortiusANT. I have a new laptop runnig Zwift and the that Zwift can not find "trainer-laptop". The two computers find each other over Bluetooth.
Furthermore, my Zwift on AppleTV can not find "trainer-laptop" anymore. Seems like my laptop does not beam out anything that Zwift can hear?
I have a vague memory that I did some fiddling with my "trainer-laptop" Bluetooth address or something? I can not remember anymore.
NOTE: I am running an older build: Fortius Antifier v5.2 (version on Github =Fortius Antifier v 6.7). This worked previously but not anymore.
I also tried a newer version Fortius Antifier v6.5 (version on Github=Fortius Antifier v6.7). This does not work either. I noticed a cgange in GIU and now there are Tacx and ANT CTP indicators. When running new version, Tacx indicator in blinking (and FortiusANT shows the correct values) but ANT CTP stays dead.
My command line with both versions is
`python FortiusAnt.py -a -g -H0 -t Bushido`

**Comment by WouterJD** [comment]
Please describe briefly what systems are actually used and what connections you would like to make.

**Comment by slilja** [comment]
Current (and preferred) configuration:
Tacx Bushido <--ANT--> Mac laptop1 running FortiusAnt <--Bluetooth--> Mac laptop2 running Zwift. 
This has worked earlier but I can not make it work again. 
FortiusAnt on laptop1 connects to Bushido and shows correct watts/cadence/speed, but Zwift on laptop2 can not find trainer. As if FortiusAnt is not sending any signal.

**Comment by slilja** [comment]
Here is a screenshot when I start FortiusAnt with
`python FortiusAnt.py -a -g -b -H0 -t Bushido`

![Screenshot 2023-03-15 at 19 35 09](https://user-images.githubusercontent.com/79280712/225395412-9e7103b7-c764-41b0-8ac4-5f9ee9d2f62b.png)

For some reason I get "Bluetooth interface not available"? That is definitely the problem - how to proceed form here?

**Comment by WouterJD** [comment]
That is the reason for sure.
There has been a sw issue (see module logfile...), which should be resolved in the current version.

You use 6.5 and 6.7 is available; see title on screen

**Comment by slilja** [comment]
I made a fresh install of FortiusANT on my "trainer-laptop" (erased entire machine and started from scratch). I could not even start FortiusAnt because python libraries did not install correctly ("module not found" error). Mac requires so much tweaking with Python environment that it is not worth it.
I will stop trying on Mac book and you can close this. I will try again when I get a Windows 10 machine - seems that installation there is a lot easier.

**Comment by WouterJD** [comment]
That's a pity, because you were si close!
I do not have a Mac so cannot help you

What modules are missing?
Just to give it a last shot

**Comment by slilja** [comment]
ModuleNotFoundError: No module named 'importlib.metadata'

Interestingly, everywhere on internet people refer to importlib_metadata (with underscore, not dot). If I install that module, the error remains.

**Comment by WouterJD** [comment]
I will make a patch today

**Comment by WouterJD** [comment]
Download [FortiusAnt.py](https://github.com/WouterJD/FortiusANT/blob/master/pythoncode/FortiusAnt.py) and retry
Succes!

**Comment by slilja** [comment]
Now FortiusAnt fails with
`Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug`
I think I am done with Mac version. Please close this issue.
I am trying to run FortiusAnt on a Windows machine. I downloaded exe file and it starts nicely, ANT+ connects to Bushido. However, I get also there an error (on GUI): "Bluetooth interface cannot be opened". I am using the recommended ASUS BT dongle and Zadig to configure driver - still no luck
Could you point me to an Issue where I can discuss Windows BT problem or should I create a new one?
I will keep trying few times still, but if also Windows fails then I stop using FortiusAnt - my computer skills are simply not enough to get it working

**Comment by WouterJD** [comment]
Getting BLE with Node.js to work is a precise jobs with quite some steps. It should be doable, you could ask a friend to assist.

BLE with bless is easier but requires a BLE/5 dongle.

Success for now!

**Comment by WouterJD** [comment]
Since there is no communication here, I assume can be closed.
If not happy to reopen
